/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author ankitjagtap
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Person person;

    public CreateJPanel(Person person) {
        initComponents();
        this.person = person;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblTelnum = new javax.swing.JLabel();
        lblFaxnum = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblMedrecnum = new javax.swing.JLabel();
        lblHealthbennum = new javax.swing.JLabel();
        lblBankaccnum = new javax.swing.JLabel();
        lblCertnum = new javax.swing.JLabel();
        lblVehicleid = new javax.swing.JLabel();
        lblDevid = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        lblIpadd = new javax.swing.JLabel();
        lblUniqueid = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtTelnum = new javax.swing.JTextField();
        txtFaxnum = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtMedrecnum = new javax.swing.JTextField();
        txtHealthbennum = new javax.swing.JTextField();
        txtBankaccnum = new javax.swing.JTextField();
        txtCertnum = new javax.swing.JTextField();
        txtVehicleid = new javax.swing.JTextField();
        txtDevid = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        txtIpadd = new javax.swing.JTextField();
        txtUniqueid = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtDob = new javax.swing.JFormattedTextField();
        ValName = new javax.swing.JLabel();
        ValCountry = new javax.swing.JLabel();
        ValDob = new javax.swing.JLabel();
        ValTelephone = new javax.swing.JLabel();
        ValFax = new javax.swing.JLabel();
        ValEmail = new javax.swing.JLabel();
        ValSsn = new javax.swing.JLabel();
        ValMedical = new javax.swing.JLabel();
        ValHealth = new javax.swing.JLabel();
        ValBank = new javax.swing.JLabel();
        ValCertificate = new javax.swing.JLabel();
        ValVehicle = new javax.swing.JLabel();
        ValDevice = new javax.swing.JLabel();
        ValLinkedin = new javax.swing.JLabel();
        ValUnique = new javax.swing.JLabel();
        ValIp = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        txtPath = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTitle.setBackground(new java.awt.Color(255, 255, 0));
        lblTitle.setFont(new java.awt.Font("Apple Color Emoji", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(139, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Profile");

        lblName.setText("Name:");

        lblCountry.setText("Country:");

        lblDob.setText("Date of Birth:");

        lblTelnum.setText("Telephone:");

        lblFaxnum.setText("Fax:");

        lblemail.setText("Email:");

        lblSsn.setText("SSN:");

        lblMedrecnum.setText("Medical Record Num:");

        lblHealthbennum.setText("Health Plan Beneficiary Num:");

        lblBankaccnum.setText("Bank A/C Num:");

        lblCertnum.setText("Certificate Num:");

        lblVehicleid.setText("Vehicle ID:");

        lblDevid.setText("Device ID:");

        lblLinkedin.setText("LinkedIn:");

        lblIpadd.setText("IP address:");

        lblUniqueid.setText("Unique ID:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        ValName.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValName.setForeground(new java.awt.Color(255, 0, 0));

        ValCountry.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValCountry.setForeground(new java.awt.Color(255, 0, 0));

        ValDob.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValDob.setForeground(new java.awt.Color(255, 0, 0));

        ValTelephone.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValTelephone.setForeground(new java.awt.Color(255, 0, 0));

        ValFax.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValFax.setForeground(new java.awt.Color(255, 0, 0));

        ValEmail.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValEmail.setForeground(new java.awt.Color(255, 0, 0));

        ValSsn.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValSsn.setForeground(new java.awt.Color(255, 0, 0));

        ValMedical.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValMedical.setForeground(new java.awt.Color(255, 0, 0));

        ValHealth.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValHealth.setForeground(new java.awt.Color(255, 0, 0));

        ValBank.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValBank.setForeground(new java.awt.Color(255, 0, 0));

        ValCertificate.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValCertificate.setForeground(new java.awt.Color(255, 0, 0));

        ValVehicle.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValVehicle.setForeground(new java.awt.Color(255, 0, 0));

        ValDevice.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValDevice.setForeground(new java.awt.Color(255, 0, 0));

        ValLinkedin.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValLinkedin.setForeground(new java.awt.Color(255, 0, 0));

        ValUnique.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValUnique.setForeground(new java.awt.Color(255, 0, 0));

        ValIp.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        ValIp.setForeground(new java.awt.Color(255, 0, 0));

        btnUpload.setText("Upload picture");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(lblName))
                            .addComponent(lblCountry)
                            .addComponent(lblDob)
                            .addComponent(lblTelnum)
                            .addComponent(lblMedrecnum)
                            .addComponent(lblSsn)
                            .addComponent(lblemail)
                            .addComponent(lblFaxnum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtName)
                            .addComponent(txtCountry)
                            .addComponent(txtTelnum, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtFaxnum)
                            .addComponent(txtEmail)
                            .addComponent(txtSsn)
                            .addComponent(txtMedrecnum)
                            .addComponent(txtDob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ValCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblBankaccnum))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ValDob, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                                                .addComponent(lblCertnum))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ValFax, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblDevid))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ValTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblVehicleid))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ValSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblIpadd))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ValEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblLinkedin))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ValMedical, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblUniqueid))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ValName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblHealthbennum)))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHealthbennum, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBankaccnum, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtUniqueid, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIpadd, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDevid, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVehicleid, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCertnum, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(btnSave)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpload)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(ValBank, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ValVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValUnique, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValIp, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBankaccnum, txtCertnum, txtCountry, txtDevid, txtDob, txtEmail, txtFaxnum, txtHealthbennum, txtIpadd, txtLinkedin, txtMedrecnum, txtName, txtSsn, txtTelnum, txtUniqueid, txtVehicleid});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitle)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCountry)
                                .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ValCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDob)
                                .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ValDob, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTelnum)
                                .addComponent(txtTelnum, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ValTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFaxnum)
                                .addComponent(txtFaxnum, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ValFax, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblemail)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ValEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSsn)
                                .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ValSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMedrecnum)
                            .addComponent(txtMedrecnum, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValMedical, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(213, 213, 213))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHealthbennum, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHealthbennum))
                            .addComponent(ValHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblBankaccnum)
                                .addComponent(txtBankaccnum, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ValBank, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCertnum)
                                .addComponent(txtCertnum, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ValCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblVehicleid)
                                .addComponent(txtVehicleid, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ValVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDevid)
                                .addComponent(txtDevid, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ValDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblLinkedin)
                                .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ValLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblIpadd)
                                .addComponent(txtIpadd, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ValIp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUniqueid)
                            .addComponent(txtUniqueid, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValUnique, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpload))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBankaccnum, txtCertnum, txtCountry, txtDevid, txtDob, txtEmail, txtFaxnum, txtHealthbennum, txtIpadd, txtLinkedin, txtMedrecnum, txtName, txtSsn, txtTelnum, txtUniqueid, txtVehicleid});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        boolean invalid = false;
        String NAME = "^[a-z A-Z ]{1,30}$";
        Pattern patt = Pattern.compile(NAME);
        Matcher match = patt.matcher(txtName.getText());
        if (!match.matches()) {
            ValName.setText("Invalid Name");
            invalid = true;
        } else {
            person.setName(txtName.getText());
        }
        Pattern patt1 = Pattern.compile(NAME);
        Matcher match1 = patt1.matcher(txtCountry.getText());
        if (!match1.matches()) {
            ValCountry.setText("Invalid Country");
            invalid = true;
        } else {
            person.setCountry(txtName.getText());
        }
        String DATE = "^(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])-[0-9]{4}$";
        Pattern patt2 = Pattern.compile(DATE);
        Matcher match2 = patt2.matcher(txtDob.getText());
        if (!match2.matches()) {
            ValDob.setText("Invalid Date");
            invalid = true;
        } else {
            person.setDate(txtDob.getText());
        }
        String TELNUMBER = "^\\d{1,3}-\\d{1,3}-\\d{4}$";
        Pattern patt3 = Pattern.compile(TELNUMBER);
        Matcher match3 = patt3.matcher(txtTelnum.getText());
        if (!match3.matches()) {
            ValTelephone.setText("Invalid Telephone Number");
            invalid = true;
        } else {
            person.setTel_num(txtTelnum.getText());
        }
        String FAXNUMBER = "^(\\+?\\d{1,}(\\s?|\\-?)\\d*(\\s?|\\-?)\\(?\\d{2,}\\)?(\\s?|\\-?)\\d{3,}\\s?\\d{3,})$";
        Pattern patt4 = Pattern.compile(FAXNUMBER);
        Matcher match4 = patt4.matcher(txtFaxnum.getText());
        if (!match4.matches()) {
            ValFax.setText("Invalid Fax Number");
            invalid = true;
        } else {
            person.setFax_num(txtFaxnum.getText());
        }
        String EMAIL = "^[a-zA-Z0-9]{1,30}@[a-zA-Z]{1,10}.[a-zA-Z]{1,5}$";
        Pattern patt5 = Pattern.compile(EMAIL);
        Matcher match5 = patt5.matcher(txtEmail.getText());
        if (!match5.matches()) {
            ValEmail.setText("Invalid Email address");
            invalid = true;
        } else {
            person.setEmail(txtEmail.getText());
        }
        String SSN = "^(\\d{3}-?\\d{2}-?\\d{4}|XXX-XX-XXXX)$";
        Pattern patt6 = Pattern.compile(SSN);
        Matcher match6 = patt6.matcher(txtSsn.getText());
        if (!match6.matches()) {
            ValSsn.setText("Invalid Fax Number");
            invalid = true;
        } else {
            person.setSsn(txtSsn.getText());
        }
        String MEDRECNUM = "[Mm][Rr]\\d{5,6}";
        Pattern patt7 = Pattern.compile(MEDRECNUM);
        Matcher match7 = patt7.matcher(txtMedrecnum.getText());
        if (!match7.matches()) {
            ValMedical.setText("Invalid Medical Reference Number");
            invalid = true;
        } else {
            person.setMed_rec_num(txtMedrecnum.getText());
        }
        String HELBENNUM = "^\\w{1,17}$";
        Pattern patt8 = Pattern.compile(HELBENNUM);
        Matcher match8 = patt8.matcher(txtHealthbennum.getText());
        if (!match8.matches()) {
            ValHealth.setText("Invalid Health Beneficiary Number");
            invalid = true;
        } else {
            person.setHel_ben_num(txtHealthbennum.getText());
        }
        String BANKACCNUM = "^\\w{1,17}$";
        Pattern patt9 = Pattern.compile(BANKACCNUM);
        Matcher match9 = patt9.matcher(txtBankaccnum.getText());
        if (!match9.matches()) {
            ValBank.setText("Invalid Bank Account Number");
            invalid = true;
        } else {
            person.setBan_acc_num(txtBankaccnum.getText());
        }
        String CERTNUM = "^\\w{1,17}$";
        Pattern patt10 = Pattern.compile(CERTNUM);
        Matcher match10 = patt10.matcher(txtCertnum.getText());
        if (!match10.matches()) {
            ValBank.setText("Invalid Certificate Number");
            invalid = true;
        } else {
            person.setCertificate_num(txtCertnum.getText());
        }
        String VEHICLEID = "^[0-9a-zA-Z]{4,9}$";
        Pattern patt11 = Pattern.compile(VEHICLEID);
        Matcher match11 = patt11.matcher(txtVehicleid.getText());
        if (!match11.matches()) {
            ValVehicle.setText("Invalid Vehicle ID");
            invalid = true;
        } else {
            person.setVehicle_id(txtVehicleid.getText());
        }
        String DEVID = "^\\w{1,17}$";
        Pattern patt12 = Pattern.compile(DEVID);
        Matcher match12 = patt12.matcher(txtDevid.getText());
        if (!match12.matches()) {
            ValDevice.setText("Invalid Device ID");
            invalid = true;
        } else {
            person.setDevice_id(txtDevid.getText());
        }
        String LINKEDIN = "((http|https)://)(www.)?"+"[a-zA-Z0-9@:%._\\+~#?&//=]"+"{2,256}\\.[a-z]"+"{2,6}\\b([-a-zA-Z0-9@:%"+"._\\+~#?&//=]*)";
        Pattern patt13 = Pattern.compile(LINKEDIN);
        Matcher match13 = patt13.matcher(txtLinkedin.getText());
        if (!match13.matches()) {
            ValLinkedin.setText("Invalid Linkedin URL");
            invalid = true;
        } else {
            person.setLinkedin(txtLinkedin.getText());
        }
        String IPADD = "^(?:(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(\\.(?!$)|$)){4}$";
        Pattern patt14 = Pattern.compile(IPADD);
        Matcher match14 = patt14.matcher(txtIpadd.getText());
        if (!match14.matches()) {
            ValIp.setText("Invalid IP Address");
            invalid = true;
        } else {
            person.setIp_add(txtIpadd.getText());
        }
        String UID = "^\\w{1,17}$";
        Pattern patt15 = Pattern.compile(UID);
        Matcher match15 = patt15.matcher(txtUniqueid.getText());
        if (!match15.matches()) {
            ValUnique.setText("Invalid Unique ID");
            invalid = true;
        } else {
            person.setUnique_id(txtUniqueid.getText());
        }

        if (invalid == false) {
            JOptionPane.showMessageDialog(this, "Product Information Saved.");
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File carr = chooser.getSelectedFile();
        String filename = carr.getAbsolutePath();
        txtPath.setText(filename);
        person.setFilename(filename);

    }//GEN-LAST:event_btnUploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ValBank;
    private javax.swing.JLabel ValCertificate;
    private javax.swing.JLabel ValCountry;
    private javax.swing.JLabel ValDevice;
    private javax.swing.JLabel ValDob;
    private javax.swing.JLabel ValEmail;
    private javax.swing.JLabel ValFax;
    private javax.swing.JLabel ValHealth;
    private javax.swing.JLabel ValIp;
    private javax.swing.JLabel ValLinkedin;
    private javax.swing.JLabel ValMedical;
    private javax.swing.JLabel ValName;
    private javax.swing.JLabel ValSsn;
    private javax.swing.JLabel ValTelephone;
    private javax.swing.JLabel ValUnique;
    private javax.swing.JLabel ValVehicle;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel lblBankaccnum;
    private javax.swing.JLabel lblCertnum;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDevid;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblFaxnum;
    private javax.swing.JLabel lblHealthbennum;
    private javax.swing.JLabel lblIpadd;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblMedrecnum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTelnum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniqueid;
    private javax.swing.JLabel lblVehicleid;
    private javax.swing.JLabel lblemail;
    private javax.swing.JTextField txtBankaccnum;
    private javax.swing.JTextField txtCertnum;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtDevid;
    private javax.swing.JFormattedTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxnum;
    private javax.swing.JTextField txtHealthbennum;
    private javax.swing.JTextField txtIpadd;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedrecnum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtTelnum;
    private javax.swing.JTextField txtUniqueid;
    private javax.swing.JTextField txtVehicleid;
    // End of variables declaration//GEN-END:variables
}
