/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.Person;

/**
 *
 * @author ankitjagtap
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person;

    public ViewJPanel(Person person) {
        initComponents();
        this.person = person;
        displayPerson();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitleV = new javax.swing.JLabel();
        lblNameV = new javax.swing.JLabel();
        lblCountryV = new javax.swing.JLabel();
        lblDobV = new javax.swing.JLabel();
        lblTelnumV = new javax.swing.JLabel();
        lblFaxnumV = new javax.swing.JLabel();
        lblemailV = new javax.swing.JLabel();
        lblSsnV = new javax.swing.JLabel();
        lblMedrecnumV = new javax.swing.JLabel();
        lblHealthbennumV = new javax.swing.JLabel();
        lblBankaccnumV = new javax.swing.JLabel();
        lblCertnumV = new javax.swing.JLabel();
        lblVehicleidV = new javax.swing.JLabel();
        lblDevidV = new javax.swing.JLabel();
        lblLinkedinV = new javax.swing.JLabel();
        lblIpaddV = new javax.swing.JLabel();
        lblUniqueidV = new javax.swing.JLabel();
        txtNameV = new javax.swing.JTextField();
        txtCountryV = new javax.swing.JTextField();
        txtDobV = new javax.swing.JTextField();
        txtTelnumV = new javax.swing.JTextField();
        txtFaxnumV = new javax.swing.JTextField();
        txtEmailV = new javax.swing.JTextField();
        txtSsnV = new javax.swing.JTextField();
        txtMedrecnumV = new javax.swing.JTextField();
        txtHealthbennumV = new javax.swing.JTextField();
        txtBankaccnumV = new javax.swing.JTextField();
        txtCertnumV = new javax.swing.JTextField();
        txtVehicleidV = new javax.swing.JTextField();
        txtDevidV = new javax.swing.JTextField();
        txtLinkedinV = new javax.swing.JTextField();
        txtIpaddV = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        txtUniqueidV = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTitleV.setBackground(new java.awt.Color(255, 255, 0));
        lblTitleV.setFont(new java.awt.Font("Apple Color Emoji", 1, 24)); // NOI18N
        lblTitleV.setForeground(new java.awt.Color(139, 0, 0));
        lblTitleV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleV.setText("View Profile");

        lblNameV.setText("Name:");

        lblCountryV.setText("Country:");

        lblDobV.setText("Date of Birth:");

        lblTelnumV.setText("Telephone:");

        lblFaxnumV.setText("Fax:");

        lblemailV.setText("Email:");

        lblSsnV.setText("SSN:");

        lblMedrecnumV.setText("Medical Record Num:");

        lblHealthbennumV.setText("Health Plan Beneficiary Num:");

        lblBankaccnumV.setText("Bank A/C Num:");

        lblCertnumV.setText("Certificate Num:");

        lblVehicleidV.setText("Vehicle ID:");

        lblDevidV.setText("Device ID:");

        lblLinkedinV.setText("LinkedIn:");

        lblIpaddV.setText("IP address:");

        lblUniqueidV.setText("Unique ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(lblTitleV)
                        .addGap(361, 361, 361))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCountryV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDobV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTelnumV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMedrecnumV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSsnV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblemailV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFaxnumV, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtNameV, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCountryV, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDobV, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelnumV, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFaxnumV, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailV, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSsnV, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedrecnumV, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 624, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHealthbennumV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBankaccnumV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUniqueidV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIpaddV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLinkedinV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDevidV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVehicleidV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCertnumV, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHealthbennumV, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBankaccnumV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUniqueidV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIpaddV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLinkedinV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDevidV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehicleidV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCertnumV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(152, 152, 152))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBankaccnumV, txtCertnumV, txtCountryV, txtDevidV, txtDobV, txtEmailV, txtFaxnumV, txtHealthbennumV, txtIpaddV, txtLinkedinV, txtMedrecnumV, txtNameV, txtSsnV, txtTelnumV, txtUniqueidV, txtVehicleidV});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblTitleV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameV)
                    .addComponent(txtNameV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHealthbennumV)
                    .addComponent(txtHealthbennumV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountryV)
                    .addComponent(txtCountryV, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBankaccnumV)
                    .addComponent(txtBankaccnumV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDobV)
                    .addComponent(txtDobV, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCertnumV)
                    .addComponent(txtCertnumV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelnumV)
                    .addComponent(txtTelnumV, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehicleidV)
                    .addComponent(txtVehicleidV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxnumV)
                    .addComponent(txtFaxnumV, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDevidV)
                    .addComponent(txtDevidV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemailV)
                    .addComponent(txtEmailV, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLinkedinV)
                    .addComponent(txtLinkedinV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSsnV)
                    .addComponent(txtSsnV, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIpaddV)
                    .addComponent(txtIpaddV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedrecnumV)
                    .addComponent(txtMedrecnumV, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUniqueidV)
                    .addComponent(txtUniqueidV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBankaccnumV, txtCertnumV, txtCountryV, txtDevidV, txtDobV, txtEmailV, txtFaxnumV, txtHealthbennumV, txtIpaddV, txtLinkedinV, txtMedrecnumV, txtNameV, txtSsnV, txtTelnumV, txtUniqueidV, txtVehicleidV});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBankaccnumV;
    private javax.swing.JLabel lblCertnumV;
    private javax.swing.JLabel lblCountryV;
    private javax.swing.JLabel lblDevidV;
    private javax.swing.JLabel lblDobV;
    private javax.swing.JLabel lblFaxnumV;
    private javax.swing.JLabel lblHealthbennumV;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblIpaddV;
    private javax.swing.JLabel lblLinkedinV;
    private javax.swing.JLabel lblMedrecnumV;
    private javax.swing.JLabel lblNameV;
    private javax.swing.JLabel lblSsnV;
    private javax.swing.JLabel lblTelnumV;
    private javax.swing.JLabel lblTitleV;
    private javax.swing.JLabel lblUniqueidV;
    private javax.swing.JLabel lblVehicleidV;
    private javax.swing.JLabel lblemailV;
    private javax.swing.JTextField txtBankaccnumV;
    private javax.swing.JTextField txtCertnumV;
    private javax.swing.JTextField txtCountryV;
    private javax.swing.JTextField txtDevidV;
    private javax.swing.JTextField txtDobV;
    private javax.swing.JTextField txtEmailV;
    private javax.swing.JTextField txtFaxnumV;
    private javax.swing.JTextField txtHealthbennumV;
    private javax.swing.JTextField txtIpaddV;
    private javax.swing.JTextField txtLinkedinV;
    private javax.swing.JTextField txtMedrecnumV;
    private javax.swing.JTextField txtNameV;
    private javax.swing.JTextField txtSsnV;
    private javax.swing.JTextField txtTelnumV;
    private javax.swing.JTextField txtUniqueidV;
    private javax.swing.JTextField txtVehicleidV;
    // End of variables declaration//GEN-END:variables

    private void displayPerson() {

        txtNameV.setText(person.getName());
        txtCountryV.setText(person.getCountry());
        txtDobV.setText(String.valueOf(person.getDate()));
        txtTelnumV.setText(String.valueOf(person.getTel_num()));
        txtFaxnumV.setText(String.valueOf(person.getFax_num()));
        txtEmailV.setText(person.getEmail());
        txtSsnV.setText(person.getSsn());
        txtMedrecnumV.setText(String.valueOf(person.getMed_rec_num()));
        txtHealthbennumV.setText(String.valueOf(person.getHel_ben_num()));
        txtBankaccnumV.setText(String.valueOf(person.getBan_acc_num()));
        txtCertnumV.setText(String.valueOf(person.getCertificate_num()));
        txtVehicleidV.setText(person.getVehicle_id());
        txtDevidV.setText(person.getDevice_id());
        txtLinkedinV.setText(person.getLinkedin());
        txtIpaddV.setText(String.valueOf(person.getIp_add()));
        txtUniqueidV.setText(person.getUnique_id());
        String test = person.getFilename();
        Image imgg = new ImageIcon(person.getFilename()).getImage();
        lblImage.setIcon(new ImageIcon(imgg));

    }
}
